# Generated by Django 5.2 on 2025-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
